### ISSUE TITLE
更改网站根目录引发的无法找到文件错误（Not Found cause by change root and url）

### ISSUE THREAD

**Issue by windgodm** [korilin/hexo-theme-particle#1]
修改根目录的config.yml中的url和root会导致无法找到vue.js、图片资源等问题

**Comment by korilin** [comment]
你好，我提交了新的代码修改，这可能可以解决你的问题，但它也可能带来新的不确定的问题。

### 主题代码更新

你可以更新主题的代码，但要注意你需要将主题配置文件的部分绝对路径改为相对路径，需要修改的配置如下：

- head_img
- menu下的src
- home_background

```yaml
head_img: images/avatar.png

home_background: "background-image:url('home.jpg')"

menu:
  home:
    icon:
      name: home
      theme: filled
    src:  # 此处可直接放空，也可以填写 / ，测试中两种都不会造成跳转问题
  about:
    icon:
      name: idcard
      theme: filled
    src: about  # 将原本的 /about 修改为about

```

### 文章图片修正

即便你获取了最新的主题代码，依旧无法正确获取到文章中的图片地址，因为这是由`hexo -g`命令生成的，目前我并不清楚如何在主题里对这个问题进行处理。

但你可以考虑开启官方提供的文章资源文件夹来管理你的文章资源

在主题配置文件中开启`post_asset_folder: true`，并将文章中的静态资源修改为相对路径；
详情请参考 [Hexo 资源文件夹](https://hexo.io/zh-cn/docs/asset-folders#%E6%96%87%E7%AB%A0%E8%B5%84%E6%BA%90%E6%96%87%E4%BB%B6%E5%A4%B9)
